CREATE TABLE category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL
  dia_emprestimo DATE() NOT NULL
  data_devolucao DATE() NOT NULL
);

CREATE TABLE author (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL
);

CREATE TABLE book (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  isbn VARCHAR(50),
  price DECIMAL(10,2),
  category_id BIGINT,
  CONSTRAINT fk_book_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE book_author (
  book_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  CONSTRAINT pk_book_author PRIMARY KEY (book_id, author_id),
  CONSTRAINT fk_ba_book FOREIGN KEY (book_id) REFERENCES book(id),
  CONSTRAINT fk_ba_author FOREIGN KEY (author_id) REFERENCES author(id)
);

INSERT INTO category(name) VALUES('João Pedro'),('Marco Aurélio'),('Isadora');
INSERT INTO category(dia_emprestimo) VALUES (12-08-2025), (07-04-2025), (09-01-2025);
INSERT INTO category(data_devolucao) VALUES (12-10-2025), (07-10-2025), (09-06-2025);
INSERT INTO author(name) VALUES('Autor A'),('Autor B');
INSERT INTO book(title,isbn,price,category_id) VALUES('Livro Exemplo','1234567890',49.90,1);
INSERT INTO book_author(book_id,author_id) VALUES(1,1);
